### ISSUE TITLE
Adding base entities to pointclass?

### ISSUE THREAD

**Issue by chesiren** [leops/fgdparser#2]
Hello,    
I've managed to use the nodejs package but now i've noticed there something missing... fgdparser does not parse the names of the base entities of other classes.
Could you update it to add the base class names to the parsed result?

**Comment by leops** [comment]
This is fixed in version `1.1.0`, there is now a  `parameters` field on each `Declaration` object that holds the values of additional class attributes such as `base`, `studio`, `iconsprite` and so on
